[workspace]
resolver = "2"
members = ["day-*"]

[workspace.dependencies]
dhat = "0.3.2"
criterion = { version = "0.4", features = ["html_reports"] }
rstest = "0.18.2"
rayon = "1.8.0"
indicatif = "0.17.7"
itertools = "0.12.0"

[profile.dhat]
inherits = "release"
debug = 1
